apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wg5m4ot17-dotnet-basic
  janus-idp.io/tekton: wg5m4ot17-dotnet-basic
  backstage.io/kubernetes-id: wg5m4ot17-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wg5m4ot17-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
